<?php

declare(strict_types=1);

namespace MiniShop3\Tests\Modx;

use MiniShop3\Services\Api\WebApiModxBootstrap;
use MiniShop3\Tests\Modx\Support\ExtraTestCase;

/**
 * OPTIONS bootstrap must not write session_enabled into web context.cache.php (#720 / #725).
 */
final class WebApiOptionsSessionLiveTest extends ExtraTestCase
{
    public function testPrepareForInitializeDoesNotDisableSessionsInRegeneratedContextCache(): void
    {
        unset($_SESSION);
        WebApiModxBootstrap::prepareForInitialize('OPTIONS');
        self::assertTrue(isset($_SESSION));
        self::assertSame([], $_SESSION);

        $cacheManager = $this->modx->getCacheManager();
        self::assertNotNull($cacheManager);
        $cacheManager->refresh([
            'context_settings' => ['contexts' => ['web']],
        ]);

        $file = rtrim((string) $this->modx->getOption('core_path'), '/\\')
            . '/cache/context_settings/web/context.cache.php';
        if (!is_file($file)) {
            self::markTestSkipped('web context.cache.php was not generated by refresh');
        }

        /** @var mixed $payload */
        $payload = include $file;
        self::assertIsArray($payload);
        $config = is_array($payload['config'] ?? null) ? $payload['config'] : $payload;
        self::assertIsArray($config);
        self::assertFalse(
            array_key_exists('session_enabled', $config) && $config['session_enabled'] === false,
            'Cold OPTIONS bootstrap must not leave session_enabled=false in context.cache.php'
        );
    }

    public function testInitializeOptionsMergeWouldPoisonCacheConfig(): void
    {
        // Same merge modCacheManager::generateContext uses with initialize($ctx, $options).
        $config = ['cultureKey' => 'en'];
        $poisoned = array_merge($config, ['session_enabled' => false]);
        self::assertFalse($poisoned['session_enabled']);

        $src = (string) file_get_contents(
            $this->extraCorePath() . 'src/Services/Api/WebApiModxBootstrap.php'
        );
        self::assertDoesNotMatchRegularExpression("/['\"]session_enabled['\"]\\s*=>/", $src);
    }
}
