<?php

return [
    'msOnBeforeAddToCart',
    'msOnAddToCart',
    'msOnBeforeChangeInCart',
    'msOnChangeInCart',
    'msOnBeforeRemoveFromCart',
    'msOnRemoveFromCart',
    'msOnBeforeEmptyCart',
    'msOnEmptyCart',
    'msOnGetStatusCart',

    'msOnBeforeAddToOrder',
    'msOnAddToOrder',
    'msOnBeforeValidateOrderValue',
    'msOnValidateOrderValue',
    'msOnBeforeRemoveFromOrder',
    'msOnRemoveFromOrder',
    'msOnBeforeEmptyOrder',
    'msOnEmptyOrder',
    'msOnBeforeGetOrderCost',
    'msOnGetOrderCost',
    'msOnSubmitOrder',
    'msOnBeforeChangeOrderStatus',
    'msOnChangeOrderStatus',
    'msOnBeforeGetOrderCustomer',
    'msOnGetOrderCustomer',

    'msOnBeforeCreateOrder',
    'msOnCreateOrder',
    'msOnBeforeUpdateOrder',
    'msOnUpdateOrder',
    'msOnBeforeSaveOrder',
    'msOnSaveOrder',
    'msOnBeforeRemoveOrder',
    'msOnRemoveOrder',

    'msOnBeforeCreateOrderProduct',
    'msOnCreateOrderProduct',
    'msOnBeforeUpdateOrderProduct',
    'msOnUpdateOrderProduct',
    'msOnBeforeRemoveOrderProduct',
    'msOnRemoveOrderProduct',

    'msOnGetProductPrice',
    'msOnGetProductWeight',
    'msOnGetProductFields',

    'msOnManagerCustomCssJs',
];
