<?php
/**
 * Manager API Routes for MiniShop3
 *
 * Routes for administrative API (connector.php).
 * Used in MODX manager for ExtJS/Vue interfaces.
 *
 * This file is part of the component and is updated along with it.
 *
 * DO NOT edit this file directly!
 * For custom routes use: core/config/ms3_routes_manager.custom.php
 *
 * Custom routes are loaded AFTER system routes and can override them.
 *
 * Available variables:
 * @var \MiniShop3\Router\Router $router
 * @var \MODX\Revolution\modX $modx
 *
 * @version 1.0.0
 */

use MiniShop3\Router\Middleware\AuthMiddleware;
use MiniShop3\Router\Middleware\PermissionMiddleware;
use MiniShop3\Router\Response;

$router->group('/api/mgr', function($router) use ($modx) {

    $router->get('/health', function() use ($modx) {
        return Response::success([
            'status' => 'ok',
            'version' => $modx->getOption('ms3_version', null, '1.0.0'),
            'timestamp' => time(),
            'api' => 'manager'
        ]);
    });

    $router->get('/user/info', function() use ($modx) {
        if (!$modx->user || !$modx->user->isAuthenticated('mgr')) {
            return Response::error('Unauthorized', 401);
        }

        return Response::success([
            'id' => $modx->user->get('id'),
            'username' => $modx->user->get('username'),
            'fullname' => $modx->user->get('fullname')
        ]);
    })->middleware(new AuthMiddleware($modx, 'mgr'));

    $router->group('/config', function($router) use ($modx) {
        $router->get('/page-fields/{page_key}', function($params) use ($modx) {
            $controller = new \MiniShop3\Controllers\Api\ConfigController($modx);
            return $controller->getPageFields($params);
        });
        $router->get('/page-fields/{page_key}/all', function($params) use ($modx) {
            $controller = new \MiniShop3\Controllers\Api\ConfigController($modx);
            return $controller->getAllPageFields($params);
        });
        $router->put('/page-fields/{page_key}', function($params) use ($modx) {
            $controller = new \MiniShop3\Controllers\Api\ConfigController($modx);
            return $controller->updatePageFields($params);
        });
        $router->delete('/page-fields/{page_key}/{field_name}', function($params) use ($modx) {
            $controller = new \MiniShop3\Controllers\Api\ConfigController($modx);
            return $controller->deleteFieldOverride($params);
        });
        $router->get('/sections/{page_key}', function($params) use ($modx) {
            $controller = new \MiniShop3\Controllers\Api\ConfigController($modx);
            return $controller->getSections($params);
        });
        $router->put('/sections/{page_key}', function($params) use ($modx) {
            $controller = new \MiniShop3\Controllers\Api\ConfigController($modx);
            return $controller->updateSections($params);
        });
        $router->delete('/sections/{page_key}/{section_key}', function($params) use ($modx) {
            $controller = new \MiniShop3\Controllers\Api\ConfigController($modx);
            return $controller->deleteSection($params);
        });

    });

    $router->group('/models', function($router) use ($modx) {
        $router->get('/{alias}/fields', function($params) use ($modx) {
            $alias = $params['alias'] ?? '';

            if (empty($alias)) {
                return Response::error('Model alias is required', 400);
            }

            try {
                /** @var \MiniShop3\Services\FieldConfigManager $fieldConfigManager */
                $fieldConfigManager = $modx->services->get('ms3_field_config_manager');

                $modelClass = $fieldConfigManager->getModelClassByAlias($alias);

                if (!$modelClass) {
                    return Response::error("Model alias not found: {$alias}", 404);
                }

                $fields = $fieldConfigManager->getModelFields($modelClass);

                return Response::success([
                    'model_alias' => $alias,
                    'model_class' => $modelClass,
                    'fields' => $fields,
                ]);
            } catch (\Exception $e) {
                $modx->log(\MODX\Revolution\modX::LOG_LEVEL_ERROR, '[FieldConfigManager] ' . $e->getMessage());
                return Response::error('Failed to load model fields: ' . $e->getMessage(), 500);
            }
        });

    });

    $router->group('/product-data', function($router) use ($modx) {
        $router->get('/{id}', function($params) use ($modx) {
            $controller = new \MiniShop3\Controllers\Api\ProductDataController($modx);
            return $controller->get($params);
        });
        $router->put('/{id}', function($params) use ($modx) {
            $controller = new \MiniShop3\Controllers\Api\ProductDataController($modx);
            return $controller->update($params);
        });

    }, [
        new AuthMiddleware($modx, 'mgr'),
        new PermissionMiddleware($modx, 'msproduct_save')
    ]);

    $router->group('/references', function($router) use ($modx) {
        $router->get('/vendors', function($params) use ($modx) {
            $controller = new \MiniShop3\Controllers\Api\ReferencesController($modx);
            return $controller->getVendors($params);
        });
        $router->get('/autocomplete', function($params) use ($modx) {
            $controller = new \MiniShop3\Controllers\Api\ReferencesController($modx);
            return $controller->getAutocomplete($params);
        });
        $router->get('/options', function($params) use ($modx) {
            $controller = new \MiniShop3\Controllers\Api\ReferencesController($modx);
            return $controller->getOptions($params);
        });
        $router->get('/product-option-fields', function($params) use ($modx) {
            $controller = new \MiniShop3\Controllers\Api\ReferencesController($modx);
            return $controller->getProductOptionFields($params);
        });
        $router->get('/product-field-values', function($params) use ($modx) {
            $controller = new \MiniShop3\Controllers\Api\ReferencesController($modx);
            return $controller->getProductFieldValues($params);
        });
        $router->get('/products', function($params) use ($modx) {
            $controller = new \MiniShop3\Controllers\Api\ReferencesController($modx);
            return $controller->searchProducts($params);
        });
        $router->get('/customers', function($params) use ($modx) {
            $controller = new \MiniShop3\Controllers\Api\ReferencesController($modx);
            return $controller->searchCustomers($params);
        });

    });

    $router->group('/extra-fields', function($router) use ($modx) {
        $router->get('', function($params) use ($modx) {
            try {
                /** @var \MiniShop3\Services\ExtraFieldsService $service */
                $service = new \MiniShop3\Services\ExtraFieldsService($modx);

                $class = $_GET['class'] ?? null;
                $criteria = $class ? ['class' => $class] : [];

                $fields = $service->getFields($criteria);

                return Response::success([
                    'fields' => $fields,
                    'total' => count($fields)
                ]);
            } catch (\Exception $e) {
                $modx->log(\MODX\Revolution\modX::LOG_LEVEL_ERROR, '[ExtraFields API] ' . $e->getMessage());
                return Response::error('Failed to load extra fields: ' . $e->getMessage(), 500);
            }
        });
        $router->get('/{id}', function($params) use ($modx) {
            $id = (int)($params['id'] ?? 0);

            if (!$id) {
                return Response::error('Field ID is required', 400);
            }

            $field = $modx->getObject(\MiniShop3\Model\msExtraField::class, $id);

            if (!$field) {
                return Response::error('Field not found', 404);
            }

            $data = $field->toArray();

            $extraFieldsUtil = new \MiniShop3\Utils\ExtraFields($modx);
            $data['column_exists'] = $extraFieldsUtil->columnExists($field->get('class'), $field->get('key'));

            return Response::success(['field' => $data]);
        });
        $router->post('', function($params) use ($modx) {
            try {
                $data = json_decode(file_get_contents('php://input'), true);

                if (empty($data)) {
                    return Response::error('Request body is empty', 400);
                }

                /** @var \MiniShop3\Services\ExtraFieldsService $service */
                $service = new \MiniShop3\Services\ExtraFieldsService($modx);

                $result = $service->createField($data);

                if (!$result['success']) {
                    return Response::error($result['message'], 400);
                }

                return Response::success([
                    'message' => $result['message'],
                    'field' => $result['data'],
                    'migration' => $result['migration']
                ]);
            } catch (\Exception $e) {
                $modx->log(\MODX\Revolution\modX::LOG_LEVEL_ERROR, '[ExtraFields API] ' . $e->getMessage());
                return Response::error('Failed to create field: ' . $e->getMessage(), 500);
            }
        });
        $router->put('/{id}', function($params) use ($modx) {
            $id = (int)($params['id'] ?? 0);

            if (!$id) {
                return Response::error('Field ID is required', 400);
            }

            try {
                $data = json_decode(file_get_contents('php://input'), true);

                if (empty($data)) {
                    return Response::error('Request body is empty', 400);
                }

                /** @var \MiniShop3\Services\ExtraFieldsService $service */
                $service = new \MiniShop3\Services\ExtraFieldsService($modx);

                $result = $service->updateField($id, $data);

                if (!$result['success']) {
                    return Response::error($result['message'], 400);
                }

                return Response::success([
                    'message' => $result['message'],
                    'field' => $result['data']
                ]);
            } catch (\Exception $e) {
                $modx->log(\MODX\Revolution\modX::LOG_LEVEL_ERROR, '[ExtraFields API] ' . $e->getMessage());
                return Response::error('Failed to update field: ' . $e->getMessage(), 500);
            }
        });
        $router->delete('/{id}', function($params) use ($modx) {
            $id = (int)($params['id'] ?? 0);

            if (!$id) {
                return Response::error('Field ID is required', 400);
            }

            try {
                /** @var \MiniShop3\Services\ExtraFieldsService $service */
                $service = new \MiniShop3\Services\ExtraFieldsService($modx);

                $result = $service->deleteField($id);

                if (!$result['success']) {
                    return Response::error($result['message'], 400);
                }

                return Response::success([
                    'message' => $result['message'],
                    'migration' => $result['migration']
                ]);
            } catch (\Exception $e) {
                $modx->log(\MODX\Revolution\modX::LOG_LEVEL_ERROR, '[ExtraFields API] ' . $e->getMessage());
                return Response::error('Failed to delete field: ' . $e->getMessage(), 500);
            }
        });

    }, [
        new PermissionMiddleware($modx, 'mssetting_save')
    ]);

    $router->group('/customers', function($router) use ($modx) {
        $router->get('', function($params) use ($modx) {
            $allParams = array_merge($_GET, $params);

            $controller = new \MiniShop3\Controllers\Api\Manager\CustomersController($modx);
            return $controller->getList($allParams);
        });
        $router->get('/{id}', function($params) use ($modx) {
            $controller = new \MiniShop3\Controllers\Api\Manager\CustomersController($modx);
            return $controller->get($params);
        });

        $router->put('/{id}', function($params) use ($modx) {
            $input = file_get_contents('php://input');
            $data = json_decode($input, true) ?: [];
            $data['id'] = $params['id'] ?? null;

            $controller = new \MiniShop3\Controllers\Api\Manager\CustomersController($modx);
            return $controller->update($data);
        });
        $router->delete('/{id}', function($params) use ($modx) {
            $controller = new \MiniShop3\Controllers\Api\Manager\CustomersController($modx);
            return $controller->delete($params);
        });
        $router->get('/{id}/addresses', function($params) use ($modx) {
            $controller = new \MiniShop3\Controllers\Api\Manager\CustomerAddressesController($modx);
            return $controller->getList($params);
        });
        $router->post('/{id}/addresses', function($params) use ($modx) {
            $input = file_get_contents('php://input');
            $data = json_decode($input, true) ?: [];
            $data['customer_id'] = $params['id'] ?? null;

            $controller = new \MiniShop3\Controllers\Api\Manager\CustomerAddressesController($modx);
            return $controller->create($data);
        });
        $router->put('/{id}/addresses/{address_id}', function($params) use ($modx) {
            $input = file_get_contents('php://input');
            $data = json_decode($input, true) ?: [];
            $data['customer_id'] = $params['id'] ?? null;
            $data['id'] = $params['address_id'] ?? null;

            $controller = new \MiniShop3\Controllers\Api\Manager\CustomerAddressesController($modx);
            return $controller->update($data);
        });
        $router->delete('/{id}/addresses/{address_id}', function($params) use ($modx) {
            $params['address_id'] = $params['address_id'] ?? null;

            $controller = new \MiniShop3\Controllers\Api\Manager\CustomerAddressesController($modx);
            return $controller->delete($params);
        });

    }, [
        new PermissionMiddleware($modx, 'view_document')
    ]);

    $router->group('/orders', function($router) use ($modx) {
        $router->get('', function($params) use ($modx) {
            $allParams = array_merge($_GET, $params);

            $controller = new \MiniShop3\Controllers\Api\Manager\OrdersController($modx);
            return $controller->getList($allParams);
        });
        // Create new order - must be before /{id} route
        $router->post('', function($params) use ($modx) {
            $input = file_get_contents('php://input');
            $data = json_decode($input, true) ?: [];

            $controller = new \MiniShop3\Controllers\Api\Manager\OrdersController($modx);
            return $controller->create($data);
        });
        // Filters config - must be before /{id} route
        $router->get('/filters', function($params) use ($modx) {
            $controller = new \MiniShop3\Controllers\Api\Manager\OrdersController($modx);
            return $controller->getFilters($params);
        });
        $router->get('/{id}', function($params) use ($modx) {
            $controller = new \MiniShop3\Controllers\Api\Manager\OrdersController($modx);
            return $controller->get($params);
        });
        $router->put('/{id}', function($params) use ($modx) {
            $body = json_decode(file_get_contents('php://input'), true) ?: [];
            $allParams = array_merge($params, $body, $_POST);
            $controller = new \MiniShop3\Controllers\Api\Manager\OrdersController($modx);
            return $controller->update($allParams);
        });
        $router->delete('/{id}', function($params) use ($modx) {
            $controller = new \MiniShop3\Controllers\Api\Manager\OrdersController($modx);
            return $controller->delete($params);
        });
        $router->get('/{id}/products', function($params) use ($modx) {
            $controller = new \MiniShop3\Controllers\Api\Manager\OrdersController($modx);
            return $controller->getProducts($params);
        });
        $router->post('/{id}/products', function($params) use ($modx) {
            $input = file_get_contents('php://input');
            $data = json_decode($input, true) ?: [];
            $allParams = array_merge($params, $data);

            $controller = new \MiniShop3\Controllers\Api\Manager\OrdersController($modx);
            return $controller->addProduct($allParams);
        });
        $router->put('/{id}/products/{product_id}', function($params) use ($modx) {
            $input = file_get_contents('php://input');
            $data = json_decode($input, true) ?: [];
            $allParams = array_merge($params, $data);

            $controller = new \MiniShop3\Controllers\Api\Manager\OrdersController($modx);
            return $controller->updateProduct($allParams);
        });
        $router->delete('/{id}/products/{product_id}', function($params) use ($modx) {
            $controller = new \MiniShop3\Controllers\Api\Manager\OrdersController($modx);
            return $controller->deleteProduct($params);
        });
        $router->get('/{id}/logs', function($params) use ($modx) {
            $controller = new \MiniShop3\Controllers\Api\Manager\OrdersController($modx);
            return $controller->getLogs($params);
        });

    }, [
        new PermissionMiddleware($modx, 'msorder_list')
    ]);

    // Statuses, Deliveries, Payments for dropdowns
    $router->get('/statuses', function($params) use ($modx) {
        $results = [];
        $collection = $modx->getIterator(\MiniShop3\Model\msOrderStatus::class);
        foreach ($collection as $item) {
            $data = $item->toArray();
            if (str_starts_with($data['name'], 'ms3_order_status_')) {
                $translated = $modx->lexicon($data['name']);
                if ($translated !== $data['name']) {
                    $data['name'] = $translated;
                }
            }
            $results[] = $data;
        }
        return \MiniShop3\Router\Response::success(['results' => $results])->getData();
    });

    $router->get('/deliveries', function($params) use ($modx) {
        $results = [];
        $collection = $modx->getIterator(\MiniShop3\Model\msDelivery::class, ['active' => 1]);
        foreach ($collection as $item) {
            $results[] = $item->toArray();
        }
        return \MiniShop3\Router\Response::success(['results' => $results])->getData();
    });

    $router->get('/payments', function($params) use ($modx) {
        $results = [];
        $collection = $modx->getIterator(\MiniShop3\Model\msPayment::class, ['active' => 1]);
        foreach ($collection as $item) {
            $results[] = $item->toArray();
        }
        return \MiniShop3\Router\Response::success(['results' => $results])->getData();
    });

    $router->group('/grid-config', function($router) use ($modx) {
        $router->get('/{grid_key}', function($params) use ($modx) {
            $controller = new \MiniShop3\Controllers\Api\Manager\GridConfigController($modx);
            return $controller->getConfig($params);
        });

        $router->put('/{grid_key}', function($params) use ($modx) {
            $input = file_get_contents('php://input');
            $data = json_decode($input, true) ?: [];
            $data['grid_key'] = $params['grid_key'] ?? null;

            $controller = new \MiniShop3\Controllers\Api\Manager\GridConfigController($modx);
            return $controller->saveConfig($data);
        });

        $router->post('/{grid_key}/field', function($params) use ($modx) {
            $input = file_get_contents('php://input');
            $data = json_decode($input, true) ?: [];
            $data['grid_key'] = $params['grid_key'] ?? null;

            $controller = new \MiniShop3\Controllers\Api\Manager\GridConfigController($modx);
            return $controller->addField($data);
        });

        $router->put('/{grid_key}/field/{field_name}', function($params) use ($modx) {
            $input = file_get_contents('php://input');
            $data = json_decode($input, true) ?: [];
            $data['grid_key'] = $params['grid_key'] ?? null;
            $data['field_name'] = $params['field_name'] ?? null;

            $controller = new \MiniShop3\Controllers\Api\Manager\GridConfigController($modx);
            return $controller->updateField($data);
        });
        $router->delete('/{grid_key}/{field_name}', function($params) use ($modx) {
            $controller = new \MiniShop3\Controllers\Api\Manager\GridConfigController($modx);
            return $controller->deleteField($params);
        });

    }, [
        new PermissionMiddleware($modx, 'view_document')
    ]);

    $router->group('/notifications', function($router) use ($modx) {
        $router->get('/references', function($params) use ($modx) {
            $controller = new \MiniShop3\Controllers\Api\Manager\NotificationsController($modx);
            return $controller->getReferences();
        });
        $router->get('', function($params) use ($modx) {
            $allParams = array_merge($_GET, $params);

            $controller = new \MiniShop3\Controllers\Api\Manager\NotificationsController($modx);
            return $controller->getList($allParams);
        });
        $router->get('/{id}', function($params) use ($modx) {
            $controller = new \MiniShop3\Controllers\Api\Manager\NotificationsController($modx);
            return $controller->get($params);
        });
        $router->post('', function($params) use ($modx) {
            $input = file_get_contents('php://input');
            $data = json_decode($input, true) ?: [];

            $controller = new \MiniShop3\Controllers\Api\Manager\NotificationsController($modx);
            return $controller->create($data);
        });
        $router->put('/{id}', function($params) use ($modx) {
            $input = file_get_contents('php://input');
            $data = json_decode($input, true) ?: [];
            $data['id'] = $params['id'] ?? null;

            $controller = new \MiniShop3\Controllers\Api\Manager\NotificationsController($modx);
            return $controller->update($data);
        });
        $router->delete('/{id}', function($params) use ($modx) {
            $controller = new \MiniShop3\Controllers\Api\Manager\NotificationsController($modx);
            return $controller->delete($params);
        });

    }, [
        new PermissionMiddleware($modx, 'mssetting_save')
    ]);

    $router->group('/model-fields', function($router) use ($modx) {
        $router->get('/models', function($params) use ($modx) {
            $controller = new \MiniShop3\Controllers\Api\Manager\ModelFieldsController($modx);
            return $controller->getModels();
        });
        $router->get('/visible/{model}', function($params) use ($modx) {
            $controller = new \MiniShop3\Controllers\Api\Manager\ModelFieldsController($modx);
            return $controller->getVisibleFields($params);
        });

        // Combo options routes
        $router->get('/combo-options/{model}', function($params) use ($modx) {
            $controller = new \MiniShop3\Controllers\Api\Manager\ModelFieldsController($modx);
            return $controller->getComboOptions($params);
        });
        $router->get('/combo-options/{model}/{field_name}', function($params) use ($modx) {
            $controller = new \MiniShop3\Controllers\Api\Manager\ModelFieldsController($modx);
            return $controller->getFieldComboOptions($params);
        });

        // Section routes
        $router->get('/sections/{model}', function($params) use ($modx) {
            $controller = new \MiniShop3\Controllers\Api\Manager\ModelFieldsController($modx);
            return $controller->getSections($params);
        });
        $router->post('/sections', function($params) use ($modx) {
            $input = file_get_contents('php://input');
            $data = json_decode($input, true) ?: [];

            $controller = new \MiniShop3\Controllers\Api\Manager\ModelFieldsController($modx);
            return $controller->createSection($data);
        });
        $router->put('/sections/ranks', function($params) use ($modx) {
            $input = file_get_contents('php://input');
            $data = json_decode($input, true) ?: [];

            $controller = new \MiniShop3\Controllers\Api\Manager\ModelFieldsController($modx);
            return $controller->updateSectionRanks($data);
        });
        $router->put('/sections/{id}', function($params) use ($modx) {
            $input = file_get_contents('php://input');
            $data = json_decode($input, true) ?: [];
            $data['id'] = $params['id'] ?? null;

            $controller = new \MiniShop3\Controllers\Api\Manager\ModelFieldsController($modx);
            return $controller->updateSection($data);
        });
        $router->delete('/sections/{id}', function($params) use ($modx) {
            $controller = new \MiniShop3\Controllers\Api\Manager\ModelFieldsController($modx);
            return $controller->deleteSection($params);
        });

        // Field routes
        $router->get('', function($params) use ($modx) {
            $allParams = array_merge($_GET, $params);

            $controller = new \MiniShop3\Controllers\Api\Manager\ModelFieldsController($modx);
            return $controller->getList($allParams);
        });
        $router->get('/{id}', function($params) use ($modx) {
            $controller = new \MiniShop3\Controllers\Api\Manager\ModelFieldsController($modx);
            return $controller->get($params);
        });
        $router->post('', function($params) use ($modx) {
            $input = file_get_contents('php://input');
            $data = json_decode($input, true) ?: [];

            $controller = new \MiniShop3\Controllers\Api\Manager\ModelFieldsController($modx);
            return $controller->create($data);
        });
        $router->put('/ranks', function($params) use ($modx) {
            $input = file_get_contents('php://input');
            $data = json_decode($input, true) ?: [];

            $controller = new \MiniShop3\Controllers\Api\Manager\ModelFieldsController($modx);
            return $controller->updateRanks($data);
        });
        $router->put('/{id}', function($params) use ($modx) {
            $input = file_get_contents('php://input');
            $data = json_decode($input, true) ?: [];
            $data['id'] = $params['id'] ?? null;

            $controller = new \MiniShop3\Controllers\Api\Manager\ModelFieldsController($modx);
            return $controller->update($data);
        });
        $router->delete('/{id}', function($params) use ($modx) {
            $controller = new \MiniShop3\Controllers\Api\Manager\ModelFieldsController($modx);
            return $controller->delete($params);
        });

    }, [
        new PermissionMiddleware($modx, 'mssetting_save')
    ]);

    // Utilities Gallery routes
    $router->group('/utilities/gallery', function($router) use ($modx) {
        // Regenerate thumbnails
        $router->post('/update', function($params) use ($modx) {
            $input = file_get_contents('php://input');
            $data = json_decode($input, true) ?: [];

            $response = $modx->runProcessor(
                'MiniShop3\\Processors\\Utilities\\Gallery\\Update',
                $data,
                ['processors_path' => MODX_CORE_PATH . 'components/minishop3/src/Processors/']
            );
            return $response->getResponse();
        });

    }, [
        new PermissionMiddleware($modx, 'msproductfile_generate')
    ]);

    // Import routes
    $router->group('/import', function($router) use ($modx) {
        // Get available fields for mapping
        $router->get('/fields', function($params) use ($modx) {
            $response = $modx->runProcessor(
                'MiniShop3\\Processors\\Utilities\\Import\\Fields',
                [],
                ['processors_path' => MODX_CORE_PATH . 'components/minishop3/src/Processors/']
            );
            return $response->getResponse();
        });

        // Upload CSV file
        $router->post('/upload', function($params) use ($modx) {
            $response = $modx->runProcessor(
                'MiniShop3\\Processors\\Utilities\\Import\\Upload',
                $_POST,
                ['processors_path' => MODX_CORE_PATH . 'components/minishop3/src/Processors/']
            );
            return $response->getResponse();
        });

        // Preview CSV file
        $router->post('/preview', function($params) use ($modx) {
            $input = file_get_contents('php://input');
            $data = json_decode($input, true) ?: [];

            $response = $modx->runProcessor(
                'MiniShop3\\Processors\\Utilities\\Import\\Preview',
                $data,
                ['processors_path' => MODX_CORE_PATH . 'components/minishop3/src/Processors/']
            );
            return $response->getResponse();
        });

        // Start import
        $router->post('/start', function($params) use ($modx) {
            $input = file_get_contents('php://input');
            $data = json_decode($input, true) ?: [];

            $response = $modx->runProcessor(
                'MiniShop3\\Processors\\Utilities\\Import\\Import',
                $data,
                ['processors_path' => MODX_CORE_PATH . 'components/minishop3/src/Processors/']
            );
            return $response->getResponse();
        });

        // Get import progress
        $router->get('/progress/{import_id}', function($params) use ($modx) {
            $response = $modx->runProcessor(
                'MiniShop3\\Processors\\Utilities\\Import\\Progress',
                ['import_id' => $params['import_id'] ?? ''],
                ['processors_path' => MODX_CORE_PATH . 'components/minishop3/src/Processors/']
            );
            return $response->getResponse();
        });

    }, [
        new PermissionMiddleware($modx, 'msproduct_save')
    ]);

}, [
    new AuthMiddleware($modx, 'mgr')
]);
