<?php

/**
 * WEB API Routes for MiniShop3
 *
 * Routes for frontend API (cart, orders, customers, catalog).
 * Used in new entry point: assets/components/minishop3/api.php
 *
 * Differences from Manager API (/api/mgr/):
 * - Uses token authentication instead of MODX sessions
 * - CORS support for headless frontend
 * - Rate limiting to protect against abuse
 * - Public endpoints for catalog (no authentication)
 *
 * This file is part of the component and is updated along with it.
 *
 * DO NOT edit this file directly!
 * For custom routes use: core/config/ms3_routes_web.custom.php
 * For addon fragments (one file per addon): core/config/ms3.routes.d/web/*.php
 * Loaded only via api.php — not via connector Index/Router (#384).
 *
 * Custom and addon routes are loaded AFTER system routes and can override them.
 *
 * Available variables:
 * @var \MiniShop3\Router\Router $router
 * @var \MODX\Revolution\modX $modx
 *
 * @version 1.0.0
 */

use MiniShop3\Router\Response;
use MiniShop3\Middleware\TokenMiddleware;
use MiniShop3\Middleware\CorsMiddleware;
use MiniShop3\Middleware\RateLimitMiddleware;
use MiniShop3\Middleware\ServiceCheckMiddleware;
use MiniShop3\Services\RateLimit\RateLimitStoreFactory;

$tokenMiddleware = new TokenMiddleware($modx);
$corsMiddleware = new CorsMiddleware([
    'allowed_origins' => $modx->getOption('ms3_cors_allowed_origins', null, ''),
    'allowed_methods' => ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS'],
    'allowed_headers' => ['Content-Type', 'Authorization', 'X-Requested-With', 'MS3TOKEN'],
    'allow_credentials' => true,
    'max_age' => 86400,
]);
$rateLimitMiddleware = new RateLimitMiddleware(
    $modx->getOption('ms3_rate_limit_max_attempts', null, 60),
    $modx->getOption('ms3_rate_limit_decay_seconds', null, 60),
    RateLimitStoreFactory::fromModx($modx)
);
$serviceCheckMiddleware = new ServiceCheckMiddleware($modx);
$router->group('/api/v1', function ($router) use ($modx, $tokenMiddleware) {

    $router->group('/cart', function ($router) use ($modx) {
        $router->post('/add', function ($params) use ($modx) {
            $controller = new \MiniShop3\Controllers\Api\Web\CartController($modx);
            return $controller->add($params);
        });
        $router->post('/remove', function ($params) use ($modx) {
            $controller = new \MiniShop3\Controllers\Api\Web\CartController($modx);
            return $controller->remove($params);
        });
        $router->post('/change', function ($params) use ($modx) {
            $controller = new \MiniShop3\Controllers\Api\Web\CartController($modx);
            return $controller->change($params);
        });
        $router->post('/change-option', function ($params) use ($modx) {
            $controller = new \MiniShop3\Controllers\Api\Web\CartController($modx);
            return $controller->changeOption($params);
        });
        $router->get('/get', function ($params) use ($modx) {
            $controller = new \MiniShop3\Controllers\Api\Web\CartController($modx);
            return $controller->get($params);
        });
        $router->post('/clean', function ($params) use ($modx) {
            $controller = new \MiniShop3\Controllers\Api\Web\CartController($modx);
            return $controller->clean($params);
        });
    }, [$tokenMiddleware]);

    $router->group('/order', function ($router) use ($modx) {
        $router->get('/get', function ($params) use ($modx) {
            $controller = new \MiniShop3\Controllers\Api\Web\OrderController($modx);
            return $controller->get($params);
        });
        $router->post('/add', function ($params) use ($modx) {
            $controller = new \MiniShop3\Controllers\Api\Web\OrderController($modx);
            return $controller->add($params);
        });
        $router->post('/set', function ($params) use ($modx) {
            $controller = new \MiniShop3\Controllers\Api\Web\OrderController($modx);
            return $controller->set($params);
        });
        $router->post('/remove', function ($params) use ($modx) {
            $controller = new \MiniShop3\Controllers\Api\Web\OrderController($modx);
            return $controller->remove($params);
        });
        $router->post('/submit', function ($params) use ($modx) {
            $controller = new \MiniShop3\Controllers\Api\Web\OrderController($modx);
            return $controller->submit($params);
        });
        $router->post('/clean', function ($params) use ($modx) {
            $controller = new \MiniShop3\Controllers\Api\Web\OrderController($modx);
            return $controller->clean($params);
        });
        $router->get('/cost', function ($params) use ($modx) {
            $controller = new \MiniShop3\Controllers\Api\Web\OrderController($modx);
            return $controller->getCost($params);
        });
        $router->get('/cost/cart', function ($params) use ($modx) {
            $controller = new \MiniShop3\Controllers\Api\Web\OrderController($modx);
            return $controller->getCartCost($params);
        });
        $router->get('/cost/delivery', function ($params) use ($modx) {
            $controller = new \MiniShop3\Controllers\Api\Web\OrderController($modx);
            return $controller->getDeliveryCost($params);
        });
        $router->get('/cost/payment', function ($params) use ($modx) {
            $controller = new \MiniShop3\Controllers\Api\Web\OrderController($modx);
            return $controller->getPaymentCost($params);
        });
        $router->post('/address/set', function ($params) use ($modx) {
            $controller = new \MiniShop3\Controllers\Api\Web\OrderController($modx);
            return $controller->setCustomerAddress($params);
        });
        $router->post('/address/clean', function ($params) use ($modx) {
            $controller = new \MiniShop3\Controllers\Api\Web\OrderController($modx);
            return $controller->cleanCustomerAddress($params);
        });
        $router->get('/delivery/validation-rules', function ($params) use ($modx) {
            $controller = new \MiniShop3\Controllers\Api\Web\OrderController($modx);
            return $controller->getDeliveryValidationRules($params);
        });
        $router->get('/delivery/required-fields', function ($params) use ($modx) {
            $controller = new \MiniShop3\Controllers\Api\Web\OrderController($modx);
            return $controller->getDeliveryRequiresFields($params);
        });
    }, [$tokenMiddleware]);

    $router->group('/customer', function ($router) use ($modx, $tokenMiddleware) {
        $customerAuth = static fn (): \MiniShop3\Controllers\Api\Web\CustomerAuthController =>
            new \MiniShop3\Controllers\Api\Web\CustomerAuthController($modx);

        $router->post('/login', function ($params) use ($customerAuth) {
            return $customerAuth()->loginFromRequest();
        });

        $router->post('/register', function ($params) use ($customerAuth) {
            return $customerAuth()->registerFromRequest();
        });

        $router->post('/logout', function ($params) use ($customerAuth) {
            return $customerAuth()->logout();
        }, [$tokenMiddleware]);

        $router->post('/forgot-password', function ($params) use ($customerAuth) {
            return $customerAuth()->forgotPasswordFromRequest();
        });

        $router->post('/reset-password', function ($params) use ($customerAuth) {
            return $customerAuth()->resetPasswordFromRequest();
        });

        $router->post('/add', function ($params) use ($modx) {
            $ms3 = $modx->services->get('ms3');
            $input = file_get_contents('php://input');
            $data = json_decode($input, true) ?: [];

            $controller = new \MiniShop3\Controllers\Api\Web\CustomerProfileController($modx, $ms3);
            return $controller->updateField($data);
        }, [$tokenMiddleware]);

        $router->get('/token/get', function ($params) use ($modx) {
            $ms3 = $modx->services->get('ms3');
            $ms3->initialize();
            $response = $ms3->customer->generateToken();

            if ($response['success']) {
                return Response::success($response['data'], $response['message'] ?? '');
            } else {
                return Response::error($response['message'] ?? 'Token generation failed', $response['code'] ?? 500);
            }
        });

        $router->group('/addresses', function ($router) use ($modx) {
            $router->get('', function ($params) use ($modx) {
                $controller = new \MiniShop3\Controllers\Api\Web\CustomerAddressController($modx);
                return $controller->getList($params);
            });
            $router->get('/{id}', function ($params) use ($modx) {
                $controller = new \MiniShop3\Controllers\Api\Web\CustomerAddressController($modx);
                return $controller->get($params);
            });

            $router->post('', function ($params) use ($modx) {
                $input = file_get_contents('php://input');
                $data = json_decode($input, true) ?: [];

                $controller = new \MiniShop3\Controllers\Api\Web\CustomerAddressController($modx);
                return $controller->create($data);
            });

            $router->put('/{id}', function ($params) use ($modx) {
                $input = file_get_contents('php://input');
                $data = json_decode($input, true) ?: [];

                $data['id'] = $params['id'] ?? null;

                $controller = new \MiniShop3\Controllers\Api\Web\CustomerAddressController($modx);
                return $controller->update($data);
            });
            $router->delete('/{id}', function ($params) use ($modx) {
                $controller = new \MiniShop3\Controllers\Api\Web\CustomerAddressController($modx);
                return $controller->delete($params);
            });
            $router->put('/{id}/set-default', function ($params) use ($modx) {
                $controller = new \MiniShop3\Controllers\Api\Web\CustomerAddressController($modx);
                return $controller->setDefault($params);
            });
        }, [$tokenMiddleware]);

        $router->put('/profile', function ($params) use ($modx) {
            $ms3 = $modx->services->get('ms3');
            $input = file_get_contents('php://input');
            $data = json_decode($input, true) ?: [];

            $controller = new \MiniShop3\Controllers\Api\Web\CustomerProfileController($modx, $ms3);
            return $controller->update($data);
        }, [$tokenMiddleware]);

        $router->post('/changeAddress', function ($params) use ($modx) {
            $controller = new \MiniShop3\Controllers\Api\Web\OrderController($modx);
            return $controller->changeCustomerAddress($params);
        }, [$tokenMiddleware]);

        $router->post('/email/resend-verification', function ($params) use ($modx) {
            $ms3 = $modx->services->get('ms3');
            $controller = new \MiniShop3\Controllers\Api\Web\CustomerEmailController($modx, $ms3);
            return $controller->resendVerification();
        }, [$tokenMiddleware]);
        $router->get('/email/verify', function ($params) use ($modx) {
            $ms3 = $modx->services->get('ms3');
            $controller = new \MiniShop3\Controllers\Api\Web\CustomerEmailController($modx, $ms3);
            return $controller->verify($params);
        });

        $router->post('/orders/{id}/cancel', function ($params) use ($modx) {
            $controller = new \MiniShop3\Controllers\Api\Web\CustomerOrderController($modx);
            return $controller->cancel($params);
        }, [$tokenMiddleware]);
    });

    $router->group('/product', function ($router) use ($modx) {

        $router->get('/get/{id}', function ($params) use ($modx) {
            return Response::success(['message' => 'Product get endpoint - not implemented yet', 'id' => $params['id'] ?? null]);
        });

        $router->get('/list', function ($params) use ($modx) {
            return Response::success(['message' => 'Product list endpoint - not implemented yet']);
        });
    });
    $router->get('/health', function () use ($modx) {
        return Response::success([
            'status' => 'ok',
            'version' => $modx->getOption('ms3_version', null, '1.0.0'),
            'timestamp' => time(),
            'api' => 'web'
        ]);
    });
}, [$corsMiddleware, $rateLimitMiddleware, $serviceCheckMiddleware]);
