<?php

namespace MiniShop3\Services\Customer;

use MiniShop3\Controllers\Auth\PasswordAuthProvider;
use MiniShop3\Model\msCustomer;
use MODX\Revolution\modX;
use MODX\Revolution\Mail\modMail;

/**
 * RegisterService - сервис регистрации новых клиентов
 *
 * Обрабатывает регистрацию клиентов с валидацией и созданием токена подтверждения email.
 * Используется как при явной регистрации, так и при автоматической регистрации во время заказа.
 *
 * Пример использования:
 * ```php
 * $registerService = $modx->services->get('ms3_register_service');
 *
 * $result = $registerService->register([
 *     'email' => 'user@example.com',
 *     'password' => 'secret123',
 *     'first_name' => 'Иван',
 *     'last_name' => 'Петров',
 *     'phone' => '+79991234567',
 *     'privacy_accepted' => true, // GDPR согласие
 * ]);
 *
 * if ($result['success']) {
 *     $customer = $result['customer'];
 * } else {
 *     echo $result['message'];
 * }
 * ```
 *
 * @package MiniShop3\Services
 */
class RegisterService
{
    /** @var modX */
    protected modX $modx;

    /** @var EmailVerificationService|null */
    protected ?EmailVerificationService $emailVerification = null;

    /**
     * @param modX $modx
     */
    public function __construct(modX $modx)
    {
        $this->modx = $modx;
    }

    /**
     * Установить сервис верификации email (опционально)
     *
     * @param EmailVerificationService $service
     * @return void
     */
    public function setEmailVerification(EmailVerificationService $service): void
    {
        $this->emailVerification = $service;
    }

    /**
     * Регистрация нового клиента
     *
     * Используется в:
     * - API процессоре Register (явная регистрация пользователя)
     * - Customer::getId() (автоматическая регистрация при оформлении заказа)
     *
     * @param array $data Данные клиента:
     *   - email (required)
     *   - password (optional) - если не указан, генерируется автоматически
     *   - first_name (optional)
     *   - last_name (optional)
     *   - phone (optional)
     *   - privacy_accepted (optional) - согласие на обработку ПД
     *   - token (optional) - токен сессии для привязки клиента
     *   - ip (optional) - IP адрес для GDPR
     * @return array ['success' => bool, 'message' => string, 'customer' => msCustomer|null]
     */
    public function register(array $data): array
    {
        // Валидация обязательных полей
        $email = trim($data['email'] ?? '');

        if (empty($email)) {
            return [
                'success' => false,
                'message' => $this->modx->lexicon('ms3_customer_err_email_required'),
                'customer' => null,
            ];
        }

        // Валидация формата email
        if (!filter_var($email, FILTER_VALIDATE_EMAIL)) {
            return [
                'success' => false,
                'message' => $this->modx->lexicon('ms3_customer_err_email_invalid'),
                'customer' => null,
            ];
        }

        // Проверка уникальности email
        $existing = $this->modx->getObject(msCustomer::class, ['email' => $email]);
        if ($existing) {
            return [
                'success' => false,
                'message' => $this->modx->lexicon('ms3_customer_err_email_exists'),
                'customer' => null,
            ];
        }

        // Проверка уникальности телефона (если указан)
        $phone = trim($data['phone'] ?? '');
        if (!empty($phone)) {
            $existingPhone = $this->modx->getObject(msCustomer::class, ['phone' => $phone]);
            if ($existingPhone) {
                return [
                    'success' => false,
                    'message' => $this->modx->lexicon('ms3_customer_err_phone_exists'),
                    'customer' => null,
                ];
            }
        }

        // Валидация пароля
        $password = $data['password'] ?? null;
        $autoGeneratedPassword = false;

        if (empty($password)) {
            // Автогенерация пароля (для регистрации через заказ)
            $password = bin2hex(random_bytes(8)); // 16 символов
            $autoGeneratedPassword = true;

            $this->modx->log(
                modX::LOG_LEVEL_DEBUG,
                "[RegisterService] Auto-generated password for {$email}"
            );
        } else {
            // Валидация сложности пароля
            $minLength = (int)$this->modx->getOption('ms3_customer_password_min_length', null, 8);
            if (strlen($password) < $minLength) {
                return [
                    'success' => false,
                    'message' => $this->modx->lexicon('ms3_customer_err_password_too_short', ['length' => $minLength]),
                    'customer' => null,
                ];
            }
        }

        // Создание клиента
        /** @var msCustomer $customer */
        $customer = $this->modx->newObject(msCustomer::class);

        $customer->set('email', $email);
        $customer->set('password', PasswordAuthProvider::hashPassword($password));
        $customer->set('first_name', trim($data['first_name'] ?? ''));
        $customer->set('last_name', trim($data['last_name'] ?? ''));
        $customer->set('phone', $phone);
        $customer->set('is_active', true);

        // Генерация уникального токена для сессий
        $customer->set('token', bin2hex(random_bytes(32)));

        // GDPR: Запись согласия на обработку ПД
        if (!empty($data['privacy_accepted'])) {
            $customer->set('privacy_accepted_at', date('Y-m-d H:i:s'));
            $customer->set('privacy_ip', $_SERVER['REMOTE_ADDR'] ?? null);
        }

        // Email не подтвержден
        $requireEmailVerification = (bool)$this->modx->getOption('ms3_customer_require_email_verification', null, true);
        $customer->set('email_verified_at', null);

        if (!$customer->save()) {
            return [
                'success' => false,
                'message' => $this->modx->lexicon('ms3_customer_err_save'),
                'customer' => null,
            ];
        }

        $this->modx->log(
            modX::LOG_LEVEL_INFO,
            "[RegisterService] Created customer #{$customer->id}: {$email}"
        );

        // Отправка письма с подтверждением email (если включено)
        if ($requireEmailVerification && $this->emailVerification) {
            $this->emailVerification->sendVerificationEmail($customer);
        }

        // Отправка письма с автосгенерированным паролем (если нужно)
        if ($autoGeneratedPassword) {
            $this->sendWelcomeEmail($customer, $password);
        }

        return [
            'success' => true,
            'message' => $this->modx->lexicon('ms3_customer_register_success'),
            'customer' => $customer,
            'auto_password' => $autoGeneratedPassword ? $password : null,
        ];
    }

    /**
     * Отправка приветственного письма с паролем
     *
     * @param msCustomer $customer
     * @param string $password Открытый пароль
     * @return void
     */
    protected function sendWelcomeEmail(msCustomer $customer, string $password): void
    {
        $email = $customer->get('email');
        $siteName = $this->modx->getOption('site_name');

        $subject = $this->modx->lexicon('ms3_customer_welcome_subject', ['site' => $siteName]);
        $body = $this->modx->lexicon('ms3_customer_welcome_body', [
            'email' => $email,
            'password' => $password,
            'site' => $siteName,
        ]);

        $this->modx->getService('mail', 'mail.modPHPMailer');
        $this->modx->mail->set(modMail::MAIL_BODY, $body);
        $this->modx->mail->set(modMail::MAIL_FROM, $this->modx->getOption('emailsender'));
        $this->modx->mail->set(modMail::MAIL_FROM_NAME, $siteName);
        $this->modx->mail->set(modMail::MAIL_SUBJECT, $subject);
        $this->modx->mail->address('to', $email);

        if ($this->modx->mail->send()) {
            $this->modx->log(
                modX::LOG_LEVEL_INFO,
                "[RegisterService] Welcome email sent to {$email}"
            );
        } else {
            $this->modx->log(
                modX::LOG_LEVEL_ERROR,
                "[RegisterService] Failed to send welcome email to {$email}: " . $this->modx->mail->mailer->ErrorInfo
            );
        }

        $this->modx->mail->reset();
    }

    /**
     * Валидация сложности пароля
     *
     * @param string $password
     * @return array ['valid' => bool, 'message' => string]
     */
    public function validatePassword(string $password): array
    {
        $minLength = (int)$this->modx->getOption('ms3_customer_password_min_length', null, 8);
        $requireUppercase = (bool)$this->modx->getOption('ms3_customer_password_require_uppercase', null, false);
        $requireNumber = (bool)$this->modx->getOption('ms3_customer_password_require_number', null, false);
        $requireSpecial = (bool)$this->modx->getOption('ms3_customer_password_require_special', null, false);

        if (strlen($password) < $minLength) {
            return [
                'valid' => false,
                'message' => $this->modx->lexicon('ms3_customer_err_password_too_short', ['length' => $minLength]),
            ];
        }

        if ($requireUppercase && !preg_match('/[A-Z]/', $password)) {
            return [
                'valid' => false,
                'message' => $this->modx->lexicon('ms3_customer_err_password_no_uppercase'),
            ];
        }

        if ($requireNumber && !preg_match('/[0-9]/', $password)) {
            return [
                'valid' => false,
                'message' => $this->modx->lexicon('ms3_customer_err_password_no_number'),
            ];
        }

        if ($requireSpecial && !preg_match('/[^a-zA-Z0-9]/', $password)) {
            return [
                'valid' => false,
                'message' => $this->modx->lexicon('ms3_customer_err_password_no_special'),
            ];
        }

        return ['valid' => true, 'message' => ''];
    }
}
